spring.application.name=employee-management

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#spring.h2.console.enabled=true

spring.datasource.url=jdbc:mysql://localhost:3306/employeemanagement
spring.datasource.username=root
spring.datasource.password=Nethra@131618

jwt.secret=ValfKXlxUX+K/WP+D9XaPg2oZGnEwxDnm6WCHdEebYU=
jwt.expiration=3600000